[package]
name = "hashtree"
version = "0.1.0"
authors = ["sigrvn"]
license = "MIT"
edition = "2018"
description = "A Merkle Tree implementation in Rust"
repository = "https://github.com/sigrvn/hashtree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
md5 = "0.7.0"
